In [1]:
import numpy as np

In [2]:
task1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
task1_1 = np.linspace(1, 10, num=10)
print(task1)
print(task1_1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [3]:
task2 = np.zeros((3, 3))
print(task2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
task3 = np.random.randint(1, 11, size=(5, 5))
print(task3)

[[ 7  1  9  7  9]
 [ 4  7  5  8  7]
 [ 3  5  4 10  1]
 [ 2 10  4 10 10]
 [ 5  2  4  5  5]]


In [5]:
task4 = np.random.random(size=(4, 4))
print(task4)

[[0.26909493 0.37019562 0.36284363 0.92334922]
 [0.87901855 0.30323147 0.22813416 0.54321812]
 [0.9282065  0.55613573 0.89935616 0.03953307]
 [0.68612213 0.08168539 0.49516425 0.29520402]]


In [6]:
task5 = np.random.randint(1, 11, size=(5,))
task5_1 = np.random.randint(1, 11, size=(5,))
print(task5 + task5_1)
print(task5 - task5_1)
print(task5 * task5_1)

[15 13  9 12 15]
[ 5 -1  7 -4 -5]
[50 42  8 32 50]


In [7]:
task6 = np.array([1, 2, 3, 4, 5, 6, 7])
task6_1 = np.array([7, 6, 5, 4, 3, 2, 1])
print(np.dot(task6, task6_1))

84


In [8]:
task7 = np.random.randint(1, 11, size=(2, 2))
task7_1 = np.random.randint(1, 11, size=(2, 3))
task7_2 = np.dot(task7, task7_1)
print(task7_2)

[[ 42  81  65]
 [ 85 105  70]]


In [9]:
task8 = np.random.randint(1, 11, size=(3, 3))
task8_1 = np.linalg.inv(task8)
print(task8_1)

[[-0.08312958 -0.04645477  0.15158924]
 [-0.17603912  0.13691932  0.02689487]
 [ 0.14914425 -0.00488998 -0.03667482]]


In [10]:
task9 = np.random.random(size=(4, 4))
task9_1 = task9.T
print(task9_1)

[[0.06880712 0.51733503 0.92993765 0.85037155]
 [0.25324115 0.52706249 0.79799125 0.83195063]
 [0.54413462 0.53480485 0.89232364 0.33069338]
 [0.11239097 0.20065227 0.4214712  0.33129009]]


In [11]:
task10 = np.random.randint(1, 11, size=(3, 4))
task10_1 = np.random.randint(1, 11, size=(4,))
task10_2 = np.dot(task10, task10_1)
print(task10_2)

[196 172 205]


In [12]:
task11 = np.random.random(size=(2, 3))
task11_1 = np.random.random(size=(3,))
task11_2 = np.dot(task11, task11_1)
print(task11_2)

[0.85350581 0.57047309]


In [13]:
task12 = np.random.randint(1, 11, (2, 2))
task12_1 = np.random.randint(1, 11, (2, 2))
print(task12 * task12_1)

[[12 56]
 [35 30]]


In [14]:
task13 = np.random.randint(1, 11, (2, 2))
task13_1 = np.random.randint(1, 11, (2, 2))
task13_2 = np.dot(task13, task13_1)
print(task13_2)

[[30 69]
 [42 66]]


In [15]:
task14 = np.random.randint(1, 101, (5, 5))
print(task14.sum())

1573


In [16]:
task15 = np.random.randint(1, 11, (4, 4))
task15_1 = np.random.randint(1, 11, (4, 4))
task15_2 = task15 - task15_1
print(task15_2)

[[-4  9 -5 -2]
 [ 8 -6  3 -5]
 [ 3  1  2 -3]
 [ 5  5 -3 -3]]


In [3]:
task16 = np.random.random(size=(3, 3))
task16_1 = np.sum(task16, axis=1).reshape(-1, 1)
print(task16_1)

[[1.31082506]
 [1.94635268]
 [0.40680049]]


In [18]:
task17 = np.random.randint(1, 10, (3, 4))
task17_1 = task17 ** 2
print(task17_1)

[[ 1 64  9 64]
 [81 81 16  1]
 [25 49 81 36]]


In [19]:
task18 = np.random.randint(1, 51, size=(4,))
task18_1 = np.sqrt(task18)
print(task18_1)

[5.19615242 5.65685425 5.91607978 1.41421356]
